spring.application.name=TrainingAppDir
# --- DataSource ---
spring.datasource.url=jdbc:mysql://localhost:3306/gym?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Optional but matches your config
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.connection.characterEncoding=utf8

# Security properties
security.jwt.secret-key=${JWT_SECRET_KEY}

# 1h in millisecond
security.jwt.expiration-time=3600000

# rapid security
api.rapid.host=edb-with-videos-and-images-by-ascendapi.p.rapidapi.com
api.rapid.url=https://edb-with-videos-and-images-by-ascendapi.p.rapidapi.com/api
api.rapid.key=${RAPID_KEY}

spring.config.import=optional:file:.env[.properties]